In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/Users/dev/Personal/DS & AI Class Notes/Data Sets/Logistic Regression/sonar.all-data.csv",header=None)

In [3]:
df = df.sample(frac=1)

In [4]:
df

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
100,0.0629,0.1065,0.1526,0.1229,0.1437,0.1190,0.0884,0.0907,0.2107,0.3597,...,0.0089,0.0262,0.0108,0.0138,0.0187,0.0230,0.0057,0.0113,0.0131,M
191,0.0315,0.0252,0.0167,0.0479,0.0902,0.1057,0.1024,0.1209,0.1241,0.1533,...,0.0108,0.0062,0.0044,0.0072,0.0007,0.0054,0.0035,0.0001,0.0055,M
94,0.0025,0.0309,0.0171,0.0228,0.0434,0.1224,0.1947,0.1661,0.1368,0.1430,...,0.0149,0.0077,0.0036,0.0114,0.0085,0.0101,0.0016,0.0028,0.0014,R
170,0.0134,0.0172,0.0178,0.0363,0.0444,0.0744,0.0800,0.0456,0.0368,0.1250,...,0.0094,0.0048,0.0047,0.0016,0.0008,0.0042,0.0024,0.0027,0.0041,M
70,0.0065,0.0122,0.0068,0.0108,0.0217,0.0284,0.0527,0.0575,0.1054,0.1109,...,0.0069,0.0025,0.0027,0.0052,0.0036,0.0026,0.0036,0.0006,0.0035,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,0.0095,0.0308,0.0539,0.0411,0.0613,0.1039,0.1016,0.1394,0.2592,0.3745,...,0.0181,0.0019,0.0102,0.0133,0.0040,0.0042,0.0030,0.0031,0.0033,M
63,0.0067,0.0096,0.0024,0.0058,0.0197,0.0618,0.0432,0.0951,0.0836,0.1180,...,0.0048,0.0023,0.0020,0.0040,0.0019,0.0034,0.0034,0.0051,0.0031,R
12,0.0079,0.0086,0.0055,0.0250,0.0344,0.0546,0.0528,0.0958,0.1009,0.1240,...,0.0176,0.0127,0.0088,0.0098,0.0019,0.0059,0.0058,0.0059,0.0032,R
190,0.0156,0.0210,0.0282,0.0596,0.0462,0.0779,0.1365,0.0780,0.1038,0.1567,...,0.0150,0.0060,0.0082,0.0091,0.0038,0.0056,0.0056,0.0048,0.0024,M
183,0.0096,0.0404,0.0682,0.0688,0.0887,0.0932,0.0955,0.2140,0.2546,0.2952,...,0.0237,0.0078,0.0144,0.0170,0.0012,0.0109,0.0036,0.0043,0.0018,M

In [5]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

### Func for Checking Zeros

In [6]:
def checkz(df):
    return df[df == 0].value_counts()

In [7]:
for i in df.columns:
    print(checkz(df[i]))

Series([], Name: 0, dtype: int64)
Series([], Name: 1, dtype: int64)
Series([], Name: 2, dtype: int64)
Series([], Name: 3, dtype: int64)
Series([], Name: 4, dtype: int64)
Series([], Name: 5, dtype: int64)
Series([], Name: 6, dtype: int64)
Series([], Name: 7, dtype: int64)
Series([], Name: 8, dtype: int64)
Series([], Name: 9, dtype: int64)
Series([], Name: 10, dtype: int64)
Series([], Name: 11, dtype: int64)
Series([], Name: 12, dtype: int64)
Series([], Name: 13, dtype: int64)
Series([], Name: 14, dtype: int64)
Series([], Name: 15, dtype: int64)
Series([], Name: 16, dtype: int64)
Series([], Name: 17, dtype: int64)
Series([], Name: 18, dtype: int64)
Series([], Name: 19, dtype: int64)
Series([], Name: 20, dtype: int64)
Series([], Name: 21, dtype: int64)
Series([], Name: 22, dtype: int64)
Series([], Name: 23, dtype: int64)
Series([], Name: 24, dtype: int64)
Series([], Name: 25, dtype: int64)
Series([], Name: 26, dtype: int64)
Series([], Name: 27, dtype: int64)
Series([], Name: 28, dtype: int64)
Series([], Name: 29, dtype: int64)
Series([], Name: 30, dtype: int64)
Series([], Name: 31, dtype: int64)
Series([], Name: 32, dtype: int64)
Series([], Name: 33, dtype: int64)
Series([], Name: 34, dtype: int64)
Series([], Name: 35, dtype: int64)
Series([], Name: 36, dtype: int64)
Series([], Name: 37, dtype: int64)
Series([], Name: 38, dtype: int64)
Series([], Name: 39, dtype: int64)
Series([], Name: 40, dtype: int64)
Series([], Name: 41, dtype: int64)
0.0    1
Name: 42, dtype: int64
0.0    1
Name: 43, dtype: int64
0.0    1
Name: 44, dtype: int64
0.0    1
Name: 45, dtype: int64
0.0    1
Name: 46, dtype: int64
0.0    1
Name: 47, dtype: int64
0.0    1
Name: 48, dtype: int64
0.0    1
Name: 49, dtype: int64
0.0    1
Name: 50, dtype: int64
Series([], Name: 51, dtype: int64)
Series([], Name: 52, dtype: int64)
Series([], Name: 53, dtype: int64)
Series([], Name: 54, dtype: int64)
Series([], Name: 55, dtype: int64)
Series([], Name: 56, dtype: int64)
Series([], Name: 57, dtype: int64)
Series([], Name: 58, dtype: int64)
Series([], Name: 59, dtype: int64)
Series([], Name: 60, dtype: int64)

In [8]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [9]:
clist = df.columns[0:60:1]

In [10]:
clist

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59],
           dtype='int64')

### Func for Removing Zeros But Not Applying...bcz all the samples are in b/w 0-1

In [35]:
def zeroremove(df):
    m = round(df.mean(),2)
    df.replace(0,m,inplace = True)

In [36]:
# for i in clist:
#     zeroremove(df[i])

## OD Tech

In [12]:
def odiqr(df):
    q1 = df.quantile(0.25)
    q3 = df.quantile(0.75)
    iqr = q3 - q1
    low = q1 - (1.5 * iqr)
    high = q3 + (1.5 * iqr)
    m = df.mean()
    df = df.apply(lambda x : m if x < low else (m if x > high else x ) )
    return df

In [13]:
def odmsd(df):
    m = round(df.mean(),2)
    s = round(df.std(),2)
    low = round(m-(3*s),2)
    high = round(m+(3*s),2)
    ft1 = df[df<low]
    ft2 = df[df>high]
    df = df.map(lambda x : low if x < low else (high if x > high else x ))

### Checking Skew of Each Columns

In [14]:
for i in clist:
    print(f'{i} is {df[i].skew()}')

0 is 2.131088403617927
1 is 2.155643666900284
2 is 2.6525178027721212
3 is 3.4016974370591413
4 is 2.0181405084483592
5 is 1.2481657456456892
6 is 0.9708203074544366
7 is 1.481106640375856
8 is 1.633869913128784
9 is 1.2812584154071607
10 is 0.9878128779952562
11 is 0.5886807806025769
12 is 0.7365842949556034
13 is 1.02236916852495
14 is 0.7639643127441458
15 is 0.6946708068184216
16 is 0.6544799912965884
17 is 0.525845114066359
18 is 0.2831823484291814
19 is -0.08533138360165299
20 is -0.2527412170134099
21 is -0.39228941499361275
22 is -0.5943498637949106
23 is -0.6918610071124024
24 is -0.7889086971703941
25 is -0.6715801459985963
26 is -0.6278429273258316
27 is -0.6154465982408338
28 is -0.44200695242974214
29 is -0.13238978896414622
30 is 0.2597970958332024
31 is 0.3134197888891948
32 is 0.42386370967659365
33 is 0.5632955277781282
34 is 0.5916537771446703
35 is 0.619867866356787
36 is 0.6769940604462363
37 is 1.0333664958915112
38 is 0.9088351420884582
39 is 0.861279683655796
40 is 0.8635260724515665
41 is 0.8601098037577957
42 is 0.9093169683561569
43 is 1.2350862463692718
44 is 1.366839000806347
45 is 1.7066741199233828
46 is 1.7901547936114919
47 is 1.2777216954207162
48 is 1.273384691148465
49 is 1.7617135425239494
50 is 2.7160596074774728
51 is 2.093975741472328
52 is 1.0605722830139799
53 is 1.0930899717311582
54 is 1.7899458592155895
55 is 1.7808045605717204
56 is 1.653090496345695
57 is 2.0983296811699987
58 is 1.7375056213650861
59 is 2.775754482875147

### Applying Func for Skew

In [15]:
for i in clist:
    if df[i].skew() <= 0.5:
        odmsd(df[i])
    else:
        df[i] = odiqr(df[i])

### After applying IQR on clist Columns the Skew is...

In [16]:
for i in clist:
    print(f'{i} is {df[i].skew()}')

0 is 0.8127144584689728
1 is 0.7891496869954774
2 is 0.8246232000444759
3 is 0.8237318020507842
4 is 0.7829704945137066
5 is 0.4769135489563302
6 is 0.43772719034632773
7 is 0.4836735531515573
8 is 0.6301391669982177
9 is 0.6010276012281714
10 is 0.5956316441300801
11 is 0.4441066622448994
12 is 0.5058381056868103
13 is 0.5211971526900219
14 is 0.6394912764735239
15 is 0.6946708068184216
16 is 0.6544799912965884
17 is 0.525845114066359
18 is 0.2831823484291814
19 is -0.08533138360165299
20 is -0.2527412170134099
21 is -0.39228941499361275
22 is -0.5943498637949106
23 is -0.6918610071124024
24 is -0.7889086971703941
25 is -0.6715801459985963
26 is -0.6278429273258316
27 is -0.6154465982408338
28 is -0.44200695242974214
29 is -0.13238978896414622
30 is 0.2597970958332024
31 is 0.3134197888891948
32 is 0.42386370967659365
33 is 0.5632955277781282
34 is 0.5916537771446703
35 is 0.619867866356787
36 is 0.6769940604462363
37 is 0.7863273839881907
38 is 0.6076962736484542
39 is 0.4798987755399665
40 is 0.6418355756974222
41 is 0.6283497334980147
42 is 0.4764951774641529
43 is 0.9118528541837905
44 is 1.0389104590168783
45 is 0.7834872869873882
46 is 0.7085329620266978
47 is 0.6509061728210795
48 is 0.7703899208408297
49 is 0.535810226507995
50 is 0.5652290685096943
51 is 0.6277024459103613
52 is 0.7035260287168787
53 is 0.7895837750439222
54 is 0.7832088895721494
55 is 0.713035087055552
56 is 0.9508094446803246
57 is 0.8619817288574544
58 is 0.910689145996865
59 is 0.8177273456808429

In [17]:
df

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
100,0.0629,0.038437,0.043832,0.1229,0.1437,0.1190,0.0884,0.0907,0.2107,0.3597,...,0.0089,0.0262,0.0108,0.0138,0.0187,0.00782,0.0057,0.0113,0.0131,M
191,0.0315,0.025200,0.016700,0.0479,0.0902,0.1057,0.1024,0.1209,0.1241,0.1533,...,0.0108,0.0062,0.0044,0.0072,0.0007,0.00540,0.0035,0.0001,0.0055,M
94,0.0025,0.030900,0.017100,0.0228,0.0434,0.1224,0.1947,0.1661,0.1368,0.1430,...,0.0149,0.0077,0.0036,0.0114,0.0085,0.01010,0.0016,0.0028,0.0014,R
170,0.0134,0.017200,0.017800,0.0363,0.0444,0.0744,0.0800,0.0456,0.0368,0.1250,...,0.0094,0.0048,0.0047,0.0016,0.0008,0.00420,0.0024,0.0027,0.0041,M
70,0.0065,0.012200,0.006800,0.0108,0.0217,0.0284,0.0527,0.0575,0.1054,0.1109,...,0.0069,0.0025,0.0027,0.0052,0.0036,0.00260,0.0036,0.0006,0.0035,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,0.0095,0.030800,0.053900,0.0411,0.0613,0.1039,0.1016,0.1394,0.2592,0.3745,...,0.0181,0.0019,0.0102,0.0133,0.0040,0.00420,0.0030,0.0031,0.0033,M
63,0.0067,0.009600,0.002400,0.0058,0.0197,0.0618,0.0432,0.0951,0.0836,0.1180,...,0.0048,0.0023,0.0020,0.0040,0.0019,0.00340,0.0034,0.0051,0.0031,R
12,0.0079,0.008600,0.005500,0.0250,0.0344,0.0546,0.0528,0.0958,0.1009,0.1240,...,0.0176,0.0127,0.0088,0.0098,0.0019,0.00590,0.0058,0.0059,0.0032,R
190,0.0156,0.021000,0.028200,0.0596,0.0462,0.0779,0.1365,0.0780,0.1038,0.1567,...,0.0150,0.0060,0.0082,0.0091,0.0038,0.00560,0.0056,0.0048,0.0024,M
183,0.0096,0.040400,0.068200,0.0688,0.0887,0.0932,0.0955,0.2140,0.2546,0.2952,...,0.0237,0.0078,0.0144,0.0170,0.0012,0.01090,0.0036,0.0043,0.0018,M

In [18]:
from sklearn.preprocessing import LabelEncoder

In [20]:
le = LabelEncoder()

In [21]:
df = pd.concat([df,pd.DataFrame(le.fit_transform(df[60]),columns=["TARGET"])],axis=1).drop(60,axis=1)

In [22]:
le.classes_

array(['M', 'R'], dtype=object)

In [23]:
df

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,TARGET
0,0.020000,0.0371,0.0428,0.0207,0.0954,0.09860,0.1539,0.160100,0.310900,0.211100,...,0.0027,0.0065,0.0159,0.0072,0.016700,0.01800,0.0084,0.0090,0.0032,0
1,0.045300,0.0523,0.0843,0.0689,0.1183,0.10457,0.2156,0.134799,0.333700,0.287200,...,0.0084,0.0089,0.0048,0.0094,0.019100,0.01400,0.0049,0.0052,0.0044,0
2,0.026200,0.0582,0.1099,0.1083,0.0974,0.22800,0.2431,0.134799,0.178003,0.208259,...,0.0232,0.0166,0.0095,0.0180,0.008222,0.00782,0.0164,0.0095,0.0078,1
3,0.010000,0.0171,0.0623,0.0205,0.0205,0.03680,0.1098,0.127600,0.059800,0.126400,...,0.0121,0.0036,0.0150,0.0085,0.007300,0.00500,0.0044,0.0040,0.0117,0
4,0.029164,0.0666,0.0481,0.0394,0.0590,0.06490,0.1209,0.246700,0.356400,0.445900,...,0.0031,0.0054,0.0105,0.0110,0.001500,0.00720,0.0048,0.0107,0.0094,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,0.018700,0.0346,0.0168,0.0177,0.0393,0.16300,0.2028,0.169400,0.232800,0.268400,...,0.0116,0.0098,0.0199,0.0033,0.010100,0.00650,0.0115,0.0193,0.0157,0
204,0.032300,0.0101,0.0298,0.0564,0.0760,0.09580,0.0990,0.101800,0.103000,0.215400,...,0.0061,0.0093,0.0135,0.0063,0.006300,0.00340,0.0032,0.0062,0.0067,1
205,0.052200,0.0437,0.0180,0.0292,0.0351,0.11710,0.1257,0.117800,0.125800,0.252900,...,0.0160,0.0029,0.0051,0.0062,0.008900,0.01400,0.0138,0.0077,0.0031,1
206,0.030300,0.0353,0.0490,0.0608,0.0167,0.13540,0.1465,0.112300,0.194500,0.235400,...,0.0086,0.0046,0.0126,0.0036,0.003500,0.00340,0.0079,0.0036,0.0048,0
207,0.026000,0.0363,0.0136,0.0272,0.0214,0.03380,0.0655,0.140000,0.184300,0.235400,...,0.0146,0.0129,0.0047,0.0039,0.006100,0.00400,0.0036,0.0061,0.0115,0

In [24]:
X = df.drop("TARGET",axis=1)

In [25]:
X.sample()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
65,0.0176,0.0172,0.0501,0.0285,0.0262,0.0351,0.0362,0.0535,0.0258,0.0474,...,0.0088,0.0042,0.0175,0.0171,0.0079,0.005,0.0112,0.0179,0.007941,0.0063

In [26]:
y = df["TARGET"]

In [27]:
y.sample()

122    1
Name: TARGET, dtype: int64

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold , cross_val_score
from sklearn.ensemble import RandomForestClassifier

In [29]:
import warnings
warnings.filterwarnings("ignore")

In [30]:
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,test_size=.20)

In [31]:
X.shape , Xtrain.shape , Xtest.shape

((208, 60), (166, 60), (42, 60))

In [32]:
y.shape , ytrain.shape , ytest.shape

((208,), (166,), (42,))

In [33]:
kf = KFold(n_splits=12)

In [34]:
rfc = RandomForestClassifier()

In [35]:
algo = [rfc]

### Without Feature Scaling

In [36]:
for i in algo:
    i.fit(Xtrain,ytrain)
    s = i.score(Xtest,ytest)
    print(f'{i} = {s}')

RandomForestClassifier() = 0.5238095238095238

### With Feature Scaling

In [37]:
ss = StandardScaler()

In [38]:
ss.fit(Xtrain)

StandardScaler()

In [39]:
Xtrain_ss = ss.transform(Xtrain)

In [40]:
Xtest_ss = ss.transform(Xtest)

In [41]:
for i in algo:
    i.fit(Xtrain_ss,ytrain)
    s = i.score(Xtest_ss,ytest)
    print(f'{i} = {s}')

RandomForestClassifier() = 0.5

### With Cross Validation

In [42]:
for i in algo:
    s = cross_val_score(i,X,y,cv = kf)
    print(f'{i} = {s.mean()}')

RandomForestClassifier() = 0.5147058823529411

## With XGBoost

In [43]:
from sklearn.ensemble import RandomForestClassifier 
from xgboost import XGBClassifier

In [45]:
xg = XGBClassifier(use_label_encoder=False,)

In [44]:
rfc = RandomForestClassifier(n_estimators=150,max_depth=3,max_leaf_nodes=4)

In [46]:
algo1 = [rfc , xg]

In [47]:
for i in algo1:
    print(i)

RandomForestClassifier(max_depth=3, max_leaf_nodes=4, n_estimators=150)
XGBClassifier(base_score=None, booster=None, colsample_bylevel=None,
              colsample_bynode=None, colsample_bytree=None,
              enable_categorical=False, gamma=None, gpu_id=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_delta_step=None, max_depth=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, reg_alpha=None,
              reg_lambda=None, scale_pos_weight=None, subsample=None,
              tree_method=None, use_label_encoder=False,
              validate_parameters=None, verbosity=None)

### Without Feature Scaling

In [49]:
for i in algo1:
    i.fit(Xtrain,ytrain)
    s = i.score(Xtest,ytest)
    print(f'{i} = {s}')
    print()

RandomForestClassifier(max_depth=3, max_leaf_nodes=4, n_estimators=150) = 0.5476190476190477

[16:11:43] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=8,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', use_label_encoder=False,
              validate_parameters=1, verbosity=None) = 0.5238095238095238

### With Feature Scaling

In [51]:
for i in algo1:
    i.fit(Xtrain_ss,ytrain)
    s = i.score(Xtest_ss,ytest)
    print(f'{i} = {s}')
    print()

RandomForestClassifier(max_depth=3, max_leaf_nodes=4, n_estimators=150) = 0.5

[16:12:24] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=8,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', use_label_encoder=False,
              validate_parameters=1, verbosity=None) = 0.5238095238095238

###  With Cross Validation (Boosting)

In [53]:
for i in algo1:
    s = cross_val_score(i,X,y,cv = kf)
    print(f'{i} = {s.mean()}')

RandomForestClassifier(max_depth=3, max_leaf_nodes=4, n_estimators=150) = 0.5435729847494554
[16:12:47] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:12:47] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:12:47] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:12:47] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:12:47] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:12:47] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:12:47] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:12:47] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:12:48] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:12:48] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:12:48] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:12:48] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=8,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', use_label_encoder=False,
              validate_parameters=1, verbosity=None) = 0.505718954248366